 name: Test Vue Name
  on:
    push:
      branches:
        - master
  jobs:
    gh-pages-deploy:
      name: Deploying Aye
      runs-on: ubuntu-latest
      steps:
        - name: Setup Node.js for use with actions
          uses: actions/setup-node@v1.1.0
          with:
            version:  12.x
        - name: Checkout branch
          uses: actions/checkout@v2

        - name: Clean install dependencies
          run: npm ci

        - name: Run deploy script
          run: git config user.name "Nathan Wuiske" && git config user.email "wuiske.nathan@gmail.com"

        - name: CA
          run: npm run build
            