name: Abc
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: aaa
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false 

      - name: bbbb
        run: npm install

      - name: cccc
        run: npm run build
  